version: 2
jobs:
  build:
    docker:
      - image: h3poteto/golang:1.9.4
        environment:
          GOPATH: /go
    working_directory: /go/src/github.com/h3poteto/ecs-goploy
    steps:
      - checkout
      - run:
          name: Checking golang version
          command: go version
      - restore_cache:
          name: Restoring cache - vendor
          keys:
            - vendor-{{ arch }}-{{ checksum "Gopkg.toml" }}-{{ checksum "Gopkg.lock" }}
      - run:
          name: Install packages
          command: dep ensure
      - run:
          name: Build
          command: go build
      - run:
          name: Test
          command: |
            cd deploy && go test
      - save_cache:
          name: Saving cache - vendor
          key: vendor-{{ arch }}-{{ checksum "Gopkg.toml" }}-{{ checksum "Gopkg.lock" }}
          paths:
            - "vendor"
